project_id = "akcicojkrzeirffefdet"

[functions.uber-auth]
verify_jwt = false

[functions.uber-token]
verify_jwt = false

[functions.uber-menu-refresh-webhook]
verify_jwt = false

[functions.uber-report-webhook]
verify_jwt = false

[functions.parse-report-csv]
verify_jwt = true

[functions.auto-generate-reports]
verify_jwt = false

[functions.generate-dispute]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-status]
verify_jwt = false

[functions.send-whatsapp-media]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.ultramsg-webhook]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.insee-density]
verify_jwt = false

[functions.ai-advisor]
verify_jwt = false

[functions.fetch-school-holidays]
verify_jwt = false

[functions.fetch-football-matches]
verify_jwt = false

[functions.parse-payment-report]
verify_jwt = false

[functions.parse-item-report]
verify_jwt = false

[functions.parse-payout-summary]
verify_jwt = false

[functions.parse-sales-over-time]
verify_jwt = false

[functions.parse-marketing-campaigns]
verify_jwt = false

[functions.parse-reviews-order]
verify_jwt = false

[functions.parse-reviews-item]
verify_jwt = false

[functions.parse-downtime-report]
verify_jwt = false

[functions.parse-order-history]
verify_jwt = false

[functions.parse-inaccurate-orders]
verify_jwt = false

[functions.parse-order-accuracy-summary]
verify_jwt = false

[functions.parse-item-issues-leaderboard]
verify_jwt = false

[functions.parse-conversion-report]
verify_jwt = false

[functions.generate-weekly-report]
verify_jwt = false

[functions.notify-tablet-pause]
verify_jwt = false

[functions.fetch-weather-data]
verify_jwt = false

[functions.generate-ai-report]
verify_jwt = false

[functions.validate-siret]
verify_jwt = false

[functions.fetch-bodacc]
verify_jwt = false
