project_id = "akcicojkrzeirffefdet"

[functions.uber-auth]
verify_jwt = false

[functions.uber-token]
verify_jwt = false

[functions.uber-menu-refresh-webhook]
verify_jwt = false

[functions.uber-report-webhook]
verify_jwt = false

[functions.parse-report-csv]
verify_jwt = true

[functions.auto-generate-reports]
verify_jwt = false

[functions.generate-dispute]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-whatsapp-media]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.ultramsg-webhook]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.insee-density]
verify_jwt = false

[functions.ai-advisor]
verify_jwt = false

[functions.fetch-school-holidays]
verify_jwt = false

[functions.fetch-football-matches]
verify_jwt = false

[functions.parse-payment-report]
verify_jwt = false

[functions.parse-item-report]
verify_jwt = false
