project_id = "akcicojkrzeirffefdet"

[functions.uber-auth]
verify_jwt = false

[functions.uber-token]
verify_jwt = false

[functions.uber-menu-refresh-webhook]
verify_jwt = false

[functions.uber-report-webhook]
verify_jwt = false