// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-chains.ts
import { createClient } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_chains_default = defineTool({
  name: "list_chains",
  title: "List brands (chains)",
  description: "List all restaurant brands (chains) the signed-in user has access to. Returns id, name, description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("chains").select("id, name, description").order("name");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { chains: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-restaurants.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_restaurants_default = defineTool2({
  name: "list_restaurants",
  title: "List restaurants",
  description: "List restaurants the signed-in user has access to. Optionally filter by chain_id (brand) and active status.",
  inputSchema: {
    chain_id: z.string().uuid().optional().describe("Filter by brand/chain UUID."),
    only_active: z.boolean().optional().describe("If true, only return active restaurants. Defaults to true."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ chain_id, only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("restaurants").select(
      "id, chain_id, name, city, postal_code, is_active, uber_store_id, deliveroo_store_id"
    ).order("name").limit(limit ?? 200);
    if (chain_id) query = query.eq("chain_id", chain_id);
    if (only_active !== false) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { restaurants: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-restaurant.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.78.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_restaurant_default = defineTool3({
  name: "get_restaurant",
  title: "Get restaurant details",
  description: "Fetch full details for a single restaurant by its UUID, including address, managers, and platform store IDs.",
  inputSchema: {
    restaurant_id: z2.string().uuid().describe("Restaurant UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ restaurant_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("restaurants").select("*").eq("id", restaurant_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "Restaurant not found or access denied." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { restaurant: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "akcicojkrzeirffefdet";
var mcp_default = defineMcp({
  name: "cs-delivery-performance-mcp",
  title: "CS Delivery Performance",
  version: "0.1.0",
  instructions: "Multi-tenant analytics for delivery brands (Uber Eats, Deliveroo, POS). Use `list_chains` to discover brands the user can access, `list_restaurants` to list their restaurants (optionally filtered by chain_id), and `get_restaurant` for full details on one restaurant. All tools respect the signed-in user's brand access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_chains_default, list_restaurants_default, get_restaurant_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
